package com.petly.petly_java.model;

public enum Especialidade {
    ACUPUNTURA,
    Anestesiologia,
    Cardiologia,
    CIRURGIA,
    PEQUENOS_ANIMAIS,
    DERMATOLOGIA,
    ENDOCRINOLOGIA,
    HOMEOPATIA,
    MEDICINA_INTENSIVA,
    MEDICINA_DO_COLETIVO,
    MEDICINA_ANIMAIS_SELVAGENS,
    NEFROLOGIA_E_UROLOGIA,
    OFTALMOLOGIA,
    ONCOLOGIA,
    PATOLOGIA,
    RADIOLOGIA,
    NUTROLOGIA,
    ODONTOLOGIA,
    NEUROLOGIA,
    PNEUMOLOGIA,
    FISIOTERAPIA,
    GERIATRIA
    }
