package com.petly.petly_java.model;

public enum NomeEspecialidade {
    ACUPUNTURA, ANESTESIOLOGIA, CARDIOLOGIA, CIRURGIA,
    DERMATOLOGIA, ENDOCRINOLOGIA, FISIOTERAPIA, GERIATRIA,
    HOMEOPATIA, MEDICINA_ANIMAIS_SELVAGENS, MEDICINA_DO_COLETIVO,
    MEDICINA_INTENSIVA, NEFROLOGIA_E_UROLOGIA, NEUROLOGIA,
    NUTROLOGIA, ODONTOLOGIA, OFTALMOLOGIA, PATOLOGIA,
    PEQUENOS_ANIMAIS, PNEUMOLOGIA, RADIOLOGIA
}
