-- docs/java-database-alignment.md §2.6 — RN-067: todo acesso ao prontuario via Colmeia gera log,
-- visivel ao Responsavel. Append-only por convencao de aplicacao (mesma logica de TB_LOG_ERRO).

CREATE TABLE TB_LOG_ACESSO_PRONTUARIO (
    ID_LOG_ACESSO           VARCHAR2(36) NOT NULL,
    DT_HR_ACESSO            DATE NOT NULL,
    DS_CONTEXTO_ACESSO      VARCHAR2(200),
    DS_BASE_ACESSO          VARCHAR2(30) NOT NULL,
    TB_ANIMAL_ID_ANIMAL     VARCHAR2(36) NOT NULL,
    TB_VETERINARIO_ID_VETERINARIO VARCHAR2(36) NOT NULL,
    CONSTRAINT TB_LOG_ACESSO_PRONTUARIO_PK PRIMARY KEY (ID_LOG_ACESSO)
);

ALTER TABLE TB_LOG_ACESSO_PRONTUARIO ADD CONSTRAINT CK_DS_BASE_ACESSO
    CHECK (DS_BASE_ACESSO IN ('CONSENTIMENTO_REDE', 'ATENDIMENTO_DIRETO'));

ALTER TABLE TB_LOG_ACESSO_PRONTUARIO ADD CONSTRAINT TB_LOG_ACS_TB_ANIMAL_FK FOREIGN KEY
    (TB_ANIMAL_ID_ANIMAL) REFERENCES TB_ANIMAL (ID_ANIMAL);
ALTER TABLE TB_LOG_ACESSO_PRONTUARIO ADD CONSTRAINT TB_LOG_ACS_TB_VET_FK FOREIGN KEY
    (TB_VETERINARIO_ID_VETERINARIO) REFERENCES TB_VETERINARIO (ID_VETERINARIO);
