-- docs/java-database-alignment.md §2.5 (Opcao A, decisao tomada em 2026-09-05) — RN-088/089:
-- prontuario versiona na propria tabela. Uma linha original (TB_PRONTUARIO_ID_ORIGINAL nulo) por
-- animal, mais N linhas de correcao apontando para ela; a original nunca e sobrescrita. Por isso
-- o indice unico por animal precisa virar nao-unico (um animal passa a ter N linhas).

ALTER TABLE TB_PRONTUARIO DROP CONSTRAINT TB_PRONTUARIO_PK CASCADE;
DROP INDEX TB_PRONTUARIO__IDX;

ALTER TABLE TB_PRONTUARIO ADD (
    DS_CONTEUDO_CLINICO         CLOB NOT NULL,
    TB_PRONTUARIO_ID_ORIGINAL   VARCHAR2(36),
    DT_HR_CORRECAO              DATE,
    CRMV_SOLICITANTE_CORRECAO   VARCHAR2(20),
    DS_JUSTIFICATIVA_CORRECAO   VARCHAR2(1000)
);

ALTER TABLE TB_PRONTUARIO ADD CONSTRAINT TB_PRONTUARIO_PK PRIMARY KEY (ID_PRONTUARIO);

CREATE INDEX TB_PRONTUARIO_ANIMAL_IDX ON TB_PRONTUARIO (TB_ANIMAL_ID_ANIMAL);

ALTER TABLE TB_PRONTUARIO ADD CONSTRAINT TB_PRONTUARIO_ORIGINAL_FK FOREIGN KEY
    (TB_PRONTUARIO_ID_ORIGINAL) REFERENCES TB_PRONTUARIO (ID_PRONTUARIO);
